import Head from 'next/head';

import { AppLogo } from '@/components/base/AppLogo';
import { CityInput } from '@/components/partial/CityInput';
import { Results } from '@/components/partial/Results';
import { useApp } from '@/contexts/AppContext';
import { REDUCER_VIEWS } from '@/utils/constants';

export default function Home() {
  const { appState } = useApp();

  return (
    <>
      <Head>
        <title>YAWA: Mike</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex flex-col h-screen bg-header">
        <section className="flex-1">
          <div className="container mb-10">
            <AppLogo />
            <CityInput />
          </div>

          {appState.view === REDUCER_VIEWS.RESULTS && <Results />}
        </section>

        <footer className="flex-0 text-[#0B1C46] text-center mb-2">
          <p>Built with 🌶</p>
        </footer>
      </main>
    </>
  );
}
